In [110]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.utils import shuffle
from sklearn.feature_extraction.text import TfidfVectorizer


In [111]:
#Import Censored Data
censored_df=pd.read_json('../ExtractedData/input_withheldtweets.json', lines=True)

In [112]:
#import mostly not censored data
uncensored_df=pd.read_json('../Data/Mostly_Not_Censored.json', lines=True)

In [113]:
#merge and shufflem
df = pd.concat([censored_df, uncensored_df], ignore_index=True, sort=False)
df = shuffle(df)

In [114]:
df.withheld_in_countries

2522         NaN
808         [TR]
270         [DE]
578     [DE, FR]
4015         NaN
          ...   
3330         NaN
1575        [TR]
2920         NaN
868         [TR]
887         [XX]
Name: withheld_in_countries, Length: 4443, dtype: object

In [115]:
print("censored", df["withheld_in_countries"].notnull().sum())
print("uncensored", df["withheld_in_countries"].isnull().sum())

censored 2062
uncensored 2381


In [116]:
df.loc[df["withheld_in_countries"].notnull(),"withheld_in_countries",]=0
df.loc[df["withheld_in_countries"].isnull(),"withheld_in_countries",]=1

In [117]:
df_x=df["text"]
df_y=df["withheld_in_countries"]
df_x

2522    RT @OrleaksFN: J Balvin sortira dans la boutiq...
808     RT @EskiMektepli: Artık hiçbirşeyin önü alınam...
270     RT @federalreserve: Approval of application by...
578     RT @AmyMek: SHARIA FRANCE!\n\nDocumentary on M...
4015    RT @gecedusu: 2005 yılı \nFındık kg, 6,5 TL \n...
                              ...                        
3330    RT @anna_fearon: Mocking her appearance, crack...
1575    RT @Hevallo: .@bbclysedoucet Lyse, you are on ...
2920                                    @natashasantoo A🤡
868     RT @ahamitbilici: Instead of being a model of ...
887     RT @guevovenezolano: Mi hombre araña hot\n htt...
Name: text, Length: 4443, dtype: object

In [118]:
cv = CountVectorizer()

In [119]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [120]:
x_train.head()

4360                                   @HanzoR6S ty hanzo
3535    RT @Ann4Castro: vcs ligam muito pro que os out...
141     If a lying progressive\nlike Franklin Delano R...
4102                                           お風呂怖いが；；；；
2598                              @lxsMinho 👀 La sorpresa
Name: text, dtype: object

In [121]:
cv = CountVectorizer()

In [122]:
x_traincv=cv.fit_transform(x_train)
x_train.iloc[0]



'@HanzoR6S ty hanzo'

In [123]:
x_testcv=cv.transform(x_test)

In [124]:
x_testcv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [125]:
mnb = MultinomialNB()

In [126]:

y_train=y_train.astype('int')
y_train

4360    1
3535    1
141     1
4102    1
2598    1
       ..
4305    1
511     0
2349    1
3964    1
4275    1
Name: withheld_in_countries, Length: 3554, dtype: int32

In [127]:
mnb.fit(x_traincv,y_train)

MultinomialNB()

In [128]:
testmessage=x_test.iloc[0]
testmessage

'RT @3alamsks: #مترجم محارم ينيك اخته وهي نائمة #حصري\n#سكس\n#six\nالرابط لمشاهدة الفيلم كامل  \n https://t.co/TSela7a9Hz\nالرابط الثاني للفيلم…'

In [129]:
predictions=mnb.predict(x_testcv)
predictions

array([0])

In [130]:
a=np.array(y_test)
a

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,

In [131]:
count=0
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1
count

1

In [132]:
len(predictions)

1

In [133]:
count/predictions

C:\Users\liamb\AppData\Local\Temp\ipykernel_16412\3678357631.py:1: RuntimeWarning: divide by zero encountered in true_divide
  count/predictions


array([inf])